Repository apu52/Travel_Website, pull requests merged in 2024-01, with the labels that each got.

#45 Shivam's nav bar
  index.html
  styles.css
Labels: help wanted

#76 Added Rating System
  feedback.html
  feedback.js
  index.html
  style_.css
Labels: help wanted

#124 Added Animations
  .vscode/settings.json
  index.html
Labels: enhancement, JWOC, Medium

#131 BUG : Alignment Fixed
  styles.css
Labels: bug, JWOC, Easy

#141 added branding
  login.html
Labels: help wanted

#150 faq page
  faq.html
  index.html
  styles.css
Labels: help wanted

#161 embedded map
  index.html
Labels: enhancement, JWOC, Medium

#180 Added favicon icon to the pages
  faq.html
  feedback.html
  login.html
  payment.html
  plantrip.html
Labels: help wanted

#187 overflow fixed
  index.html
Labels: bug, JWOC, Easy

#197 Created feedback form properly
  feed.css
  feed.html
  index.html
  styles.css
  thankyou.html
Labels: help wanted

#186 Dark theme added
  Theme.js
  index.html
  styles.css
Labels: bug, JWOC, Medium

#194 Local installation video
  README.md
Labels: help wanted

#217 [ISSUE - 38] Top destination slider
  img/eiffelTower.webp
  index.html
  index.js
  styles.css
Labels: help wanted
