Repository apu52/Travel_Website, pull requests merged in 2024-05, with the labels that each got.

#411 plantrip , about page (add-ups) and navbar responsiveness
  index.html
  plantrip.html
Labels: WAITING

#424 Improved the hover effect
  styles.css
Labels: WAITING

#431 fixed routing bug
  index.html
Labels: gssoc

#434 solved the copyrightBUG_index.html
  index.html
Labels: bug, level1, gssoc

#457 Responsive contact us
  styles.css
Labels: help wanted

#446 Fixed Slow Hover Transition Effect on Trip Cards issue #433
  styles.css
Labels: help wanted

#593 Updated chatbot
  index.html
Labels: help wanted, WAITING

#552 Added new plantrip page
  Tourguide (2).jpg
  index.html
  newplantrip.html
  newplantripstyle.css
  ronin-06roiCfSCiU-unsplash (1).jpg
Labels: help wanted, WAITING
