Repository apu52/Travel_Website, pull requests merged in 2024-06, with the labels that each got.

#624 added scroll up button
  index.html
  styles.css
Labels: help wanted, WAITING

#631 after click on book now on start.html page checkout need to be aligned
  dedicated-destinations/bali/bali.css
Labels: help wanted, question, WAITING

#618 Added new Login Page and Registration page
  index.html
  loginPage.css
  loginPage.html
  registerPage.css
  registerPage.html
Labels: help wanted, question

#636 Fix: Made hero section responsive.
  styles.css
Labels: help wanted, question

#761 fix: BUG UI Enhancement of Image Gallery
  imstyle.css
  index.html
  jquery.flipster.min.css
  jquery.flipster.min.js
  styles.css
Labels: help wanted

#871 feat: Introducing Google maps
  index.html
  mapa.html
  maps.css
  maps.js
Labels: help wanted, WAITING

#773 feat: Added search bar and price filter in the pricing page
  notFound.jpg
  package.html
Labels: help wanted

#797 feat: Resolved Dark Mode Persistance Issue After refreshing
  Theme.js
Labels: help wanted

#813 feat: UI of rate us page improved with better alignment and css styles
  feedback.html
  img/background.png
  img/bgrate.jpg
  img/rateus.jpg
  style_.css
Labels: help wanted

#893 feat: Added social media links
  index.html
  styles.css
Labels: help wanted
