Repository apu52/Travel_Website, pull requests merged in 2024-07, with the labels that each got.

#818 fix: fixed mobile view of home page
  index.html
  styles.css
Labels: help wanted

#958 feat: Added 3d parallax tilty effect on cards
  index.html
  tilt.css
  tilt.js
Labels: enhancement, level1, gssoc

#942 feat: Counter added, Numeric status section improved
  counter.css
  index.html
  index.js
  style.css
  styles.css
Labels: help wanted

#926 feat: FAQ Page inproved
  counter.css
  faq-website.css
  faq-website.js
  faq.html
  index.html
  style.css
Labels: help wanted

#935 feat: Created a pop up for discount for trip packages webpage
  package.html
  styles.css
Labels: enhancement, WAITING, gssoc

#972 fix: Issue #796 fixed Destination Section
  index.html
Labels: help wanted

#999 fix: added logo
  Untitled (1).mp4
  index.html
  story.html
  style.css
Labels: help wanted

#1017 feat: add effect on mentioned section
  explore.css
  explore.js
  index.html
  styles.css
Labels: help wanted

#1051 feat: Footer hover effect updated
  styles.css
Labels: help wanted

#1023 fix: Redirecting to the desired url instead of /story page.
  index.html
Labels: help wanted

#1035 feat: Scroll down progress bar added
  index.html
Labels: help wanted

#1029 feat: Added a Back-To Home Button on The Login Page
  newLogin.css
  newLogin.html
Labels: enhancement, WAITING, gssoc

#946 feat: Trip Gallery Page is Been Updated
  index.html
Labels: help wanted

#1116 feat: UI Enhancement and Bug Fixed in Story Page
  story.html
Labels: help wanted

#951 feat: Replaced previous website logo
  img/A T logo with a white background and a square shape, connected to nature for a travel company.png
  img/Travel.png
  img/tour1.png
  index.html
  styles.css
Labels: help wanted

#1123 fix: Footer of Trip Package page fixed
  index.html
  package.html
Labels: help wanted

#1138 feat: Enhancing About Section
  Image-Gallery/style.css
  styles.css
Labels: help wanted

#1148 fix: Nav-bar in story page
  story.html
Labels: help wanted

#1158 feat: Modified custom scrollbar .
  index.html
  styles.css
Labels: help wanted

#1204 feat: Added Cookie Pop-up to the Website
  index.html
Labels: enhancement, WAITING, gssoc

#1176 feat: Made the changes for the google transulate
  index.html
Labels: help wanted

#1228 feat: Enhance License and Acknowledgments Section and Project mentor section
  README.md
Labels: help wanted

#1229 feat: dark mode in membership page
  pricing/index.html
  pricing/style.css
Labels: help wanted
